services:

  mongo:
    image: mongo
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ADMINUSERNAME}
    #   - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ADMINPASSWORD}
    #   - MONGO_INITDB_DATABASE=${DATABASE_NAME}
    volumes:
      - shared-data:/shared
    ports:
      - "27017:27017"
    networks:
      - server-net
    deploy:
      resources:
        limits:
          cpus: '0.5'       # half CPU core
          memory: 512M      # 512 MB RAM
        reservations:
          cpus: '0.25'      # minimum CPU reserved
          memory: 256M      # minimum memory reserved

volumes:
  shared-data: