export enum USER_ROLES {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  SERVICE_PROVIDER = 'SERVICE_PROVIDER',
  USER = 'USER',
}

export enum ACCOUNT_STATUS {
  ACTIVE = 'ACTIVE',
  INACTIVE = "INACTIVE"
}

export enum SELECTED_LANGUAGE {
  GERMAN = 'GERMAN',
  TURKISH = 'TURKISH',
  ENGLISH = 'ENGLISH',
  SPANISH = 'SPANISH'
}

export enum ACCOUNT_VERIFICATION_STATUS {
  VERIFIED = 'true',
  UNVERIFIED = 'false'
}