export enum USER_ROLES {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  SERVICE_PROVIDER = 'SERVICE_PROVIDER',
  USER = 'USER',
}

export enum ACCOUTN_ACTVITY_STATUS {
  ACTIVE = 'ACTIVE',
  INACTIVE = "INACTIVE"
}

export enum ACCOUNT_STATUS {
  ACTIVE = 'ACTIVE',
  BLOCK = 'BLOCK',
  REPORT = 'REPORT'
}

export enum SELECTED_LANGUAGE {
  ENGLISH = 'en',
  GERMAN = 'de',
  TURKISH = 'tr',
  SPANISH = 'es',
}

export enum ACCOUNT_VERIFICATION_STATUS {
  VERIFIED = 'true',
  UNVERIFIED = 'false'
}